In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score, mean_squared_error

In [2]:
y_NN2 = pd.read_excel('y_NN2.xlsx')

In [3]:
y_NN2.head()

MLFF  GRNN  SUM  AVG
0     7     6   13  6.5
1     6     6   12  6.0
2     7     6   13  6.5
3     6     6   12  6.0
4     5     5   10  5.0

In [4]:
y_NN2 = y_NN2.round().astype(int)

In [5]:
df = pd.read_csv('winequality-white.csv')

In [6]:
data = df.drop('quality', axis = 1)
target = df['quality']

In [7]:
x_train, x_test, y_train, y_test = train_test_split(data, target, train_size=0.75, random_state = 123)

In [8]:
print(confusion_matrix(y_test, y_NN2['AVG']))

[[  0   0   3   1   0   0   0]
 [  0  13  14  11   0   0   0]
 [  0  27 181 154   0   0   0]
 [  0  10  90 467   6   1   0]
 [  0   1  11 160  25   1   0]
 [  0   0   0  35  11   0   0]
 [  0   0   0   2   1   0   0]]


In [9]:
print(classification_report(y_test, y_NN2['AVG']))

             precision    recall  f1-score   support

          3       0.00      0.00      0.00         4
          4       0.25      0.34      0.29        38
          5       0.61      0.50      0.55       362
          6       0.56      0.81      0.67       574
          7       0.58      0.13      0.21       198
          8       0.00      0.00      0.00        46
          9       0.00      0.00      0.00         3

avg / total       0.54      0.56      0.52      1225



C:\Users\purpl\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1113: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [10]:
score = accuracy_score(y_test, y_NN2['AVG'])
print("Validation accuracy: {:.2%}".format(score))

Validation accuracy: 56.00%


In [11]:
mse = mean_squared_error(y_test, y_NN2['AVG'])
print("MSE: {:.2%}".format(mse))

MSE: 64.24%


In [12]:
y_Ens2 = pd.read_excel('y_Ens2.xlsx')

In [13]:
y_Ens2.head()

MLFF  GRNN  LOG  QDA  RFC  SVM  SUM       AVG
0     7     6    6    7    6    6   38  6.333333
1     6     6    6    7    7    7   39  6.500000
2     7     6    6    7    7    6   39  6.500000
3     6     6    6    7    7    7   39  6.500000
4     5     5    5    5    5    6   31  5.166667

In [14]:
y_Ens2 = y_Ens2.round().astype(int)

In [15]:
print(confusion_matrix(y_test, y_Ens2['AVG']))

[[  0   0   2   2   0   0   0]
 [  0   2  27   9   0   0   0]
 [  0   0 213 148   1   0   0]
 [  0   0  86 476  12   0   0]
 [  0   0   7 145  46   0   0]
 [  0   0   0  23  23   0   0]
 [  0   0   0   2   1   0   0]]


In [16]:
print(classification_report(y_test, y_Ens2['AVG']))

             precision    recall  f1-score   support

          3       0.00      0.00      0.00         4
          4       1.00      0.05      0.10        38
          5       0.64      0.59      0.61       362
          6       0.59      0.83      0.69       574
          7       0.55      0.23      0.33       198
          8       0.00      0.00      0.00        46
          9       0.00      0.00      0.00         3

avg / total       0.59      0.60      0.56      1225



C:\Users\purpl\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1113: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [17]:
score = accuracy_score(y_test, y_Ens2['AVG'])
print("Validation accuracy: {:.2%}".format(score))

Validation accuracy: 60.16%


In [18]:
mse = mean_squared_error(y_test, y_Ens2['AVG'])
print("MSE: {:.2%}".format(mse))

MSE: 52.98%
