In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score, mean_squared_error

In [2]:
df = pd.read_csv('winequality-white.csv')

In [3]:
df.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.0              0.27         0.36            20.7      0.045   
1            6.3              0.30         0.34             1.6      0.049   
2            8.1              0.28         0.40             6.9      0.050   
3            7.2              0.23         0.32             8.5      0.058   
4            7.2              0.23         0.32             8.5      0.058   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 45.0                 170.0   1.0010  3.00       0.45   
1                 14.0                 132.0   0.9940  3.30       0.49   
2                 30.0                  97.0   0.9951  3.26       0.44   
3                 47.0                 186.0   0.9956  3.19       0.40   
4                 47.0                 186.0   0.9956  3.19       0.40   

   alcohol  quality  
0      8.8        6  
1      9.5        6  
2     10.1        6  
3      9.9        6  
4      9.9        6

In [4]:
df.describe()

fixed acidity  volatile acidity  citric acid  residual sugar  \
count    4898.000000       4898.000000  4898.000000     4898.000000   
mean        6.854788          0.278241     0.334192        6.391415   
std         0.843868          0.100795     0.121020        5.072058   
min         3.800000          0.080000     0.000000        0.600000   
25%         6.300000          0.210000     0.270000        1.700000   
50%         6.800000          0.260000     0.320000        5.200000   
75%         7.300000          0.320000     0.390000        9.900000   
max        14.200000          1.100000     1.660000       65.800000   

         chlorides  free sulfur dioxide  total sulfur dioxide      density  \
count  4898.000000          4898.000000           4898.000000  4898.000000   
mean      0.045772            35.308085            138.360657     0.994027   
std       0.021848            17.007137             42.498065     0.002991   
min       0.009000             2.000000              9.000000     0.987110   
25%       0.036000            23.000000            108.000000     0.991723   
50%       0.043000            34.000000            134.000000     0.993740   
75%       0.050000            46.000000            167.000000     0.996100   
max       0.346000           289.000000            440.000000     1.038980   

                pH    sulphates      alcohol      quality  
count  4898.000000  4898.000000  4898.000000  4898.000000  
mean      3.188267     0.489847    10.514267     5.877909  
std       0.151001     0.114126     1.230621     0.885639  
min       2.720000     0.220000     8.000000     3.000000  
25%       3.090000     0.410000     9.500000     5.000000  
50%       3.180000     0.470000    10.400000     6.000000  
75%       3.280000     0.550000    11.400000     6.000000  
max       3.820000     1.080000    14.200000     9.000000

In [5]:
data = df.drop('quality', axis = 1)
target = df['quality']

In [6]:
x_train, x_test, y_train, y_test = train_test_split(data, target, train_size=0.75, random_state = 123)

In [7]:
from sklearn.ensemble import RandomForestClassifier

In [8]:
rfc = RandomForestClassifier(n_estimators=10000, class_weight='balanced')

In [9]:
rfc.fit(x_train, y_train)

RandomForestClassifier(bootstrap=True, class_weight='balanced',
            criterion='gini', max_depth=None, max_features='auto',
            max_leaf_nodes=None, min_impurity_split=1e-07,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10000, n_jobs=1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [10]:
y_predicted = rfc.predict(x_test)

In [11]:
print(confusion_matrix(y_test, y_predicted))

[[  0   0   1   3   0   0   0]
 [  0   8  21   9   0   0   0]
 [  0   1 245 113   3   0   0]
 [  0   2  81 453  38   0   0]
 [  0   0   8  81 107   2   0]
 [  0   0   0  12  18  16   0]
 [  0   0   0   2   1   0   0]]


In [12]:
print(classification_report(y_test, y_predicted))

             precision    recall  f1-score   support

          3       0.00      0.00      0.00         4
          4       0.73      0.21      0.33        38
          5       0.69      0.68      0.68       362
          6       0.67      0.79      0.73       574
          7       0.64      0.54      0.59       198
          8       0.89      0.35      0.50        46
          9       0.00      0.00      0.00         3

avg / total       0.68      0.68      0.67      1225



C:\Users\purpl\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1113: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [13]:
score = accuracy_score(y_test, y_predicted)
print("Validation accuracy: {:.2%}".format(score))

Validation accuracy: 67.67%


In [14]:
mse = mean_squared_error(y_test, pd.DataFrame(y_predicted))
print("MSE: {:.2%}".format(mse))

MSE: 44.41%


In [15]:
y_RFC2 = pd.DataFrame(y_predicted)
y_RFC2.to_excel('y_RFC2.xlsx')